name: CSV Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: 'Sélectionner l’environnement'
        required: true
        default: 'dev'

jobs:
  csv_pipeline:
    runs-on: ubuntu-latest

    # Utilise la matrice uniquement pour les environnements [dev, test, prod]
    strategy:
      matrix:
        env: [dev, test, prod]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Utilise une version Python spécifique (3.11.x) pour tous les jobs de la matrice
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas  # Installe pandas pour tous les scripts

      # Exécute le script correspondant à l'environnement en cours (dev, test, ou prod)
      - name: Run Python script for ${{ matrix.env }}
        run: |
          if [ "${{ matrix.env }}" == "dev" ]; then
            python scripts/csv_to_dev.py
          elif [ "${{ matrix.env }}" == "test" ]; then
            python scripts/csv_to_test.py
          elif [ "${{ matrix.env }}" == "prod" ]; then
            python scripts/csv_to_prod.py
          fi
