name: Lecture CSV selon environnement

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choisir l’environnement : dev, test ou prod'
        required: true
        default: 'dev'

jobs:
  read-csv-job:
    runs-on: ubuntu-latest
    env:
      # Passe la sélection utilisateur à une variable d'environnement
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pandas # Assurez-vous que cette ligne est correcte si vous n'utilisez pas requirements.txt

      - name: Run Python script
        # Le script Python doit lire la variable $ENVIRONMENT pour choisir le fichier
        run: python scripts/read_csv.py
